"""Сторонние модули, привязанные к платформам (извлечены из original third_party.py)."""

THIRD_PARTY_WINDOWS = {
    "zlib1.dll": "Zlib Compression Library (Windows)",
    "libcurl.dll": "Curl Library (Windows)",
    "sqlite3.dll": "SQLite Database Engine (Windows)",
    "libeay32.dll": "OpenSSL Encryption Library (Windows)",
    "ssleay32.dll": "OpenSSL SSL/TLS Library (Windows)",
    "libsodium.dll": "Libsodium (Windows)",
    "libzip.dll": "Libzip (Windows)",
    "libmysql.dll": "MySQL Connector/C (Windows)",
    "libpq.dll": "Libpq (Windows)",
    "libssh2.dll": "Libssh2 (Windows)",
    "nghttp2.dll": "Nghttp2 (Windows)",
    "sdl2.dll": "SDL2 (Windows)",
    "opencv_core.dll": "OpenCV Core Module (Windows)",
    "opencv_imgproc.dll": "OpenCV Image Processing Module (Windows)",
    "log4cplus.dll": "Log4cplus (Windows)",
    "log4cxx.dll": "Log4cxx (Windows)",
    "log4net.dll": "Log4net (Windows)",
    "libpdf.dll": "PDF Library (Windows)",
    "tcg.dll": "QEMU Tiny Code Generator (TCG) (Windows)",
    "wireguard.dll": "WireGuard VPN (Windows)",
    "libwg.dll": "WireGuard Library (Windows)",
    "openvpn.dll": "OpenVPN Client Library (Windows)",
    "qt5core.dll": "Qt5 Core (Windows)",
    "qt5gui.dll": "Qt5 GUI (Windows)",
    "qt5widgets.dll": "Qt5 Widgets (Windows)",
    "qt6core.dll": "Qt6 Core (Windows)",
    "qt6gui.dll": "Qt6 GUI (Windows)",
    "tensorflow.dll": "TensorFlow C API (Windows)",
    "onnxruntime.dll": "ONNX Runtime (Windows)",
    "grpc.dll": "gRPC (Windows)",
    "protobuf.dll": "Protocol Buffers (Windows)",
    "v8.dll": "Google V8 JavaScript Engine (Windows)",
    "libjpeg-8.dll": "LibJPEG (Windows)",
    "libpng16.dll": "LibPNG (Windows)",
    "libtiff-5.dll": "LibTIFF (Windows)",
    "libwebp.dll": "LibWebP (Windows)",
    "libvips-42.dll": "LibVips (Windows)",
    "ImageMagick.dll": "ImageMagick (Windows)",
    "libGraphicsMagick-3.Q16.dll": "GraphicsMagick (Windows)",
    "libopenjp2.dll": "OpenJPEG (Windows)",
    "libraw.dll": "LibRaw (Windows)",
    "libjxl.dll": "LibJXL (Windows)",
    "libmpg123.dll": "libmpg123 (Windows)",
    "libmp3lame.dll": "LAME (Windows)",
    "libvorbis.dll": "LibVorbis (Windows)",
    "libvorbisfile.dll": "LibVorbisFile (Windows)",
    "libogg.dll": "LibOgg (Windows)",
    "libopus.dll": "Opus (Windows)",
    "libFLAC.dll": "FLAC (Windows)",
    "libsndfile-1.dll": "LibSndFile (Windows)",
    "openal32.dll": "OpenAL (Windows)",
    "libportaudio-2.dll": "PortAudio (Windows)",
    "libsoxr.dll": "libsoxr (Windows)",
    "opencv_world480.dll": "OpenCV World (Windows)",
    "opencv_core480.dll": "OpenCV Core (Windows)",
    "opencv_imgproc480.dll": "OpenCV Image Processing (Windows)",
    "opencv_dnn480.dll": "OpenCV DNN (Windows)",
    "opencv_face480.dll": "OpenCV Face (Windows)",
    "opencv_objdetect480.dll": "OpenCV Object Detection (Windows)",
    "opencv_calib3d480.dll": "OpenCV Calib3D (Windows)",
    "libtorch.dll": "LibTorch (Windows)",
    "torch_cuda.dll": "Torch CUDA (Windows)",
    "tensorflow_lite.dll": "TensorFlow Lite (Windows)",
    "caffe.dll": "Caffe (Windows)",
    "libopenblas.dll": "OpenBLAS (Windows)",
    "libarmadillo.dll": "Armadillo (Windows)",
    "libgsl.dll": "GSL (Windows)",
    "libfftw3.dll": "FFTW (Windows)",
    "libgmp-10.dll": "GMP (Windows)",
    "libmpfr.dll": "MPFR (Windows)",
    "libnvinfer.dll": "NVIDIA TensorRT (Windows)",
    "libzmq.dll": "ZeroMQ (Windows)",
    "libnanomsg.dll": "Nanomsg (Windows)",
    "libnng.dll": "NNG (Windows)",
    "librabbitmq.dll": "RabbitMQ C Client (Windows)",
    "libkafka.dll": "librdkafka (Windows)",
    "libmsgpackc.dll": "MessagePack (Windows)",
    "libavlrcodec.dll": "Avro C (Windows)",
    "libcapnp.dll": "Cap'n Proto (Windows)",
    "flatbuffers.dll": "FlatBuffers (Windows)",
    "libBulletDynamics.dll": "Bullet Physics (Windows)",
    "libBulletCollision.dll": "Bullet Collision (Windows)",
    "libgodot-cpp.dll": "Godot Engine (Windows)",
    "libOgreMain.dll": "OGRE 3D (Windows)",
    "libIrrlicht.dll": "Irrlicht (Windows)",
    "libosg.dll": "OpenSceneGraph (Windows)",
    "libavcodec.dll": "FFmpeg libavcodec (Windows)",
    "libavformat.dll": "FFmpeg libavformat (Windows)",
    "libavutil.dll": "FFmpeg libavutil (Windows)",
    "libswscale.dll": "FFmpeg libswscale (Windows)",
    "libswresample.dll": "FFmpeg libswresample (Windows)",
    "libvlc.dll": "LibVLC (Windows)",
    "libvlccore.dll": "LibVLC Core (Windows)",
    "libgstreamer-1.0-0.dll": "GStreamer (Windows)",
    "libtag.dll": "TagLib (Windows)",
    "libcdio.dll": "libcdio (Windows)",
    "cairo.dll": "Cairo (Windows)",
    "libpixman-1-0.dll": "Pixman (Windows)",
    "librsvg-2-2.dll": "librsvg (Windows)",
    "libSkia.dll": "Skia (Windows)",
    "libqrencode.dll": "libqrencode (Windows)",
    "libzxing.dll": "ZXing (Windows)",
    "libwx_mswu_core-3.2.dll": "wxWidgets (Windows)",
    "libfltk.dll": "FLTK (Windows)",
    "libnuklear.dll": "Nuklear (Windows)",
    "libimgui.dll": "Dear ImGui (Windows)",
    "libIUP.dll": "IUP (Windows)",
    "libnana.dll": "Nana C++ Library (Windows)",
    "libncursesw6.dll": "Ncurses (Windows)",
    "libpanelw6.dll": "Panel (Windows)",
    "libformw6.dll": "Form (Windows)",
    "libmenuw6.dll": "Menu (Windows)",
    "libreadline8.dll": "GNU Readline (Windows)",
    "liblz4.dll": "LZ4 (Windows)",
    "libzstd.dll": "Zstandard (Windows)",
    "libbrotlicommon.dll": "Brotli (Windows)",
    "libbrotlienc.dll": "Brotli Encoder (Windows)",
    "libbrotlidec.dll": "Brotli Decoder (Windows)",
    "libsnappy.dll": "Snappy (Windows)",
    "libzopfli.dll": "Zopfli (Windows)",
    "libminizip.dll": "Minizip (Windows)",
    "libunrar.dll": "UnRAR (Windows)",
    "libarchive.dll": "libarchive (Windows)",
    "libcryptopp.dll": "Crypto++ (Windows)",
    "libmbedtls.dll": "Mbed TLS (Windows)",
    "libmbedcrypto.dll": "Mbed Crypto (Windows)",
    "libmbedx509.dll": "Mbed X.509 (Windows)",
    "libwolfssl.dll": "wolfSSL (Windows)",
    "libgpg-error.dll": "Libgpg-error (Windows)",
    "libgpgme-11.dll": "GPGME (Windows)",
    "libtasn1.dll": "Libtasn1 (Windows)",
    # OpenSSL 1.1+ — современные имена DLL (ранее хранились в windows.py)
    "libcrypto-1_1-x64.dll": "OpenSSL 1.1+ Encryption Library (64-bit)",
    "libssl-1_1-x64.dll": "OpenSSL 1.1+ SSL/TLS Library (64-bit)",
    "libcrypto-1_1.dll": "OpenSSL 1.1+ Encryption Library (32-bit)",
    "libssl-1_1.dll": "OpenSSL 1.1+ SSL/TLS Library (32-bit)",
    "libcrypto-3-x64.dll": "OpenSSL 3.x Encryption Library (64-bit)",
    "libssl-3-x64.dll": "OpenSSL 3.x SSL/TLS Library (64-bit)",
    "libcrypto-3.dll": "OpenSSL 3.x Encryption Library (32-bit)",
    "libssl-3.dll": "OpenSSL 3.x SSL/TLS Library (32-bit)",
}

THIRD_PARTY_LINUX = {
    "libcurl.so.4": "Curl Library (Linux)",
    "libnghttp2.so.14": "Nghttp2 (Linux)",
    "libssh2.so.1": "Libssh2 (Linux)",
    "libsdl2.so.0": "SDL2 (Linux)",
    "libopencv_core.so": "OpenCV Core (Linux)",
    "libgtk-3.so.0": "GTK+ 3 (Linux)",
    "libgtk-4.so.1": "GTK 4 (Linux)",
    "liblog4cplus.so": "Log4cplus (Linux)",
    "libtcg.so": "QEMU TCG (Linux)",
    "libwg.so": "WireGuard (Linux)",
    "libopenvpn.so": "OpenVPN (Linux)",
    "libqt5core.so": "Qt5 Core (Linux)",
    "libqt5gui.so": "Qt5 GUI (Linux)",
    "libqt5widgets.so": "Qt5 Widgets (Linux)",
    "libtorch.so": "LibTorch (Linux)",
    "libtensorflow_lite.so": "TensorFlow Lite (Linux)",
    "libcaffe.so": "Caffe (Linux)",
    "libopenblas.so.0": "OpenBLAS (Linux)",
    "libarmadillo.so.10": "Armadillo (Linux)",
    "libgsl.so.25": "GSL (Linux)",
    "libfftw3.so.3": "FFTW (Linux)",
    "libnvinfer.so.10": "TensorRT (Linux)",
    "libzmq.so.5": "ZeroMQ (Linux)",
    "libnanomsg.so.5": "Nanomsg (Linux)",
    "libnng.so.1": "NNG (Linux)",
    "librabbitmq.so.4": "RabbitMQ C Client (Linux)",
    "librdkafka.so.1": "librdkafka (Linux)",
    "libmsgpackc.so.2": "MessagePack (Linux)",
    "libavro.so.23": "Avro C (Linux)",
    "libcapnp.so.1": "Cap'n Proto (Linux)",
    "libflatbuffers.so.1": "FlatBuffers (Linux)",
    "libBulletDynamics.so.3.25": "Bullet Physics (Linux)",
    "libBulletCollision.so": "Bullet Collision (Linux)",
    "libgodot-cpp.so": "Godot Engine (Linux)",
    "libOgreMain.so.1.12": "OGRE 3D (Linux)",
    "libIrrlicht.so.1.8": "Irrlicht (Linux)",
    "libosg.so.161": "OpenSceneGraph (Linux)",
    "libavcodec.so.60": "FFmpeg libavcodec (Linux)",
    "libavformat.so.60": "FFmpeg libavformat (Linux)",
    "libavutil.so.58": "FFmpeg libavutil (Linux)",
    "libswscale.so.7": "FFmpeg libswscale (Linux)",
    "libswresample.so.4": "FFmpeg libswresample (Linux)",
    "libvlc.so.5": "LibVLC (Linux)",
    "libvlccore.so.9": "LibVLC Core (Linux)",
    "libgstreamer-1.0.so.0": "GStreamer (Linux)",
    "libtag.so.1": "TagLib (Linux)",
    "libcdio.so.19": "libcdio (Linux)",
    "libqrencode.so.4": "libqrencode (Linux)",
    "libzxing.so": "ZXing (Linux)",
    "libwx_gtk3u_core-3.2.so.0": "wxWidgets (Linux)",
    "libfltk.so.1.3": "FLTK (Linux)",
    "libnuklear.so": "Nuklear (Linux)",
    "libimgui.so": "Dear ImGui (Linux)",
    "libiup.so": "IUP (Linux)",
    "libnana.so": "Nana C++ Library (Linux)",
    "libbrotlicommon.so.1": "Brotli (Linux)",
    "libbrotlienc.so": "Brotli Encoder (Linux)",
    "libbrotlidec.so": "Brotli Decoder (Linux)",
    "libzopfli.so.1": "Zopfli (Linux)",
    "libminizip.so.1": "Minizip (Linux)",
    "libunrar.so.5": "UnRAR (Linux)",
    "libarchive.so.13": "libarchive (Linux)",
    "libsodium.so.23": "Libsodium (Linux)",
    "libcryptopp.so.8": "Crypto++ (Linux)",
    "libmbedtls.so.14": "Mbed TLS (Linux)",
    "libmbedcrypto.so.7": "Mbed Crypto (Linux)",
    "libmbedx509.so": "Mbed X.509 (Linux)",
    "libwolfssl.so.35": "wolfSSL (Linux)",
    "libgpgme.so.11": "GPGME (Linux)",
    "libtasn1.so.6": "Libtasn1 (Linux)",
}

THIRD_PARTY_MACOS = {
    "libssl.dylib": "OpenSSL SSL/TLS Library (macOS)",
    "libpng.dylib": "LibPNG (macOS)",
    "libjpeg.dylib": "LibJPEG (macOS)",
    "libtiff.dylib": "LibTIFF (macOS)",
    "libwebp.dylib": "LibWebP (macOS)",
    "libvips.dylib": "LibVips (macOS)",
    "ImageMagick.dylib": "ImageMagick (macOS)",
    "GraphicsMagick.dylib": "GraphicsMagick (macOS)",
    "libopenjp2.dylib": "OpenJPEG (macOS)",
    "libraw.dylib": "LibRaw (macOS)",
    "libjxl.dylib": "LibJXL (macOS)",
    "libmpg123.dylib": "libmpg123 (macOS)",
    "libmp3lame.dylib": "LAME (macOS)",
    "libvorbis.dylib": "LibVorbis (macOS)",
    "libvorbisfile.dylib": "LibVorbisFile (macOS)",
    "libogg.dylib": "LibOgg (macOS)",
    "libopus.dylib": "Opus (macOS)",
    "libFLAC.dylib": "FLAC (macOS)",
    "libsndfile.dylib": "LibSndFile (macOS)",
    "libopenal.dylib": "OpenAL (macOS)",
    "libportaudio.dylib": "PortAudio (macOS)",
    "libsoxr.dylib": "libsoxr (macOS)",
    "opencv_core.dylib": "OpenCV Core (macOS)",
    "opencv_imgproc.dylib": "OpenCV Image Processing (macOS)",
    "libtorch.dylib": "LibTorch (macOS)",
    "tensorflow_lite.dylib": "TensorFlow Lite (macOS)",
    "caffe.dylib": "Caffe (macOS)",
    "libopenblas.dylib": "OpenBLAS (macOS)",
    "libarmadillo.dylib": "Armadillo (macOS)",
    "libgsl.dylib": "GSL (macOS)",
    "libfftw3.dylib": "FFTW (macOS)",
    "libgmp.dylib": "GMP (macOS)",
    "libmpfr.dylib": "MPFR (macOS)",
    "libzmq.dylib": "ZeroMQ (macOS)",
    "libnanomsg.dylib": "Nanomsg (macOS)",
    "libnng.dylib": "NNG (macOS)",
    "librabbitmq.dylib": "RabbitMQ C Client (macOS)",
    "librdkafka.dylib": "librdkafka (macOS)",
    "libmsgpackc.dylib": "MessagePack (macOS)",
    "libavro.dylib": "Avro C (macOS)",
    "libcapnp.dylib": "Cap'n Proto (macOS)",
    "flatbuffers.dylib": "FlatBuffers (macOS)",
    "libBulletDynamics.dylib": "Bullet Physics (macOS)",
    "libBulletCollision.dylib": "Bullet Collision (macOS)",
    "libgodot-cpp.dylib": "Godot Engine (macOS)",
    "libOgreMain.dylib": "OGRE 3D (macOS)",
    "libIrrlicht.dylib": "Irrlicht (macOS)",
    "libosg.dylib": "OpenSceneGraph (macOS)",
    "libavcodec.dylib": "FFmpeg libavcodec (macOS)",
    "libavformat.dylib": "FFmpeg libavformat (macOS)",
    "libavutil.dylib": "FFmpeg libavutil (macOS)",
    "libswscale.dylib": "FFmpeg libswscale (macOS)",
    "libswresample.dylib": "FFmpeg libswresample (macOS)",
    "libvlc.dylib": "LibVLC (macOS)",
    "libvlccore.dylib": "LibVLC Core (macOS)",
    "libgstreamer.dylib": "GStreamer (macOS)",
    "libtag.dylib": "TagLib (macOS)",
    "libcdio.dylib": "libcdio (macOS)",
    "cairo.dylib": "Cairo (macOS)",
    "libpixman-1.dylib": "Pixman (macOS)",
    "librsvg-2.dylib": "librsvg (macOS)",
    "libSkia.dylib": "Skia (macOS)",
    "libqrencode.dylib": "libqrencode (macOS)",
    "libzxing.dylib": "ZXing (macOS)",
    "libwx_osx_cocoau_core-3.2.dylib": "wxWidgets (macOS)",
    "libfltk.dylib": "FLTK (macOS)",
    "libnuklear.dylib": "Nuklear (macOS)",
    "libimgui.dylib": "Dear ImGui (macOS)",
    "libIUP.dylib": "IUP (macOS)",
    "libnana.dylib": "Nana C++ Library (macOS)",
    "libncurses.dylib": "Ncurses (macOS)",
    "libpanel.dylib": "Panel (macOS)",
    "libform.dylib": "Form (macOS)",
    "libmenu.dylib": "Menu (macOS)",
    "libreadline.dylib": "GNU Readline (macOS)",
    "liblz4.dylib": "LZ4 (macOS)",
    "libzstd.dylib": "Zstandard (macOS)",
    "libbrotlicommon.dylib": "Brotli (macOS)",
    "libbrotlienc.dylib": "Brotli Encoder (macOS)",
    "libbrotlidec.dylib": "Brotli Decoder (macOS)",
    "libsnappy.dylib": "Snappy (macOS)",
    "libzopfli.dylib": "Zopfli (macOS)",
    "libminizip.dylib": "Minizip (macOS)",
    "libunrar.dylib": "UnRAR (macOS)",
    "libarchive.dylib": "libarchive (macOS)",
    "libsodium.dylib": "Libsodium (macOS)",
    "libcryptopp.dylib": "Crypto++ (macOS)",
    "libmbedtls.dylib": "Mbed TLS (macOS)",
    "libmbedcrypto.dylib": "Mbed Crypto (macOS)",
    "libmbedx509.dylib": "Mbed X.509 (macOS)",
    "libwolfssl.dylib": "wolfSSL (macOS)",
    "libgpg-error.dylib": "Libgpg-error (macOS)",
    "libgpgme.dylib": "GPGME (macOS)",
    "libtasn1.dylib": "Libtasn1 (macOS)",
}